### ISSUE TITLE
Use $next instead of return $response so other middlewares can be executed

### ISSUE THREAD

**Issue by sandrokeil** [prooph/psr7-middleware#11]
We should always call `$next` instead of returning the response directly to allow, that other middlewares can be executed after the prooph middlewares. Here is the rule
1. Return `$response` only if an error is occured
2. Otherwise call always `$next` with the new response

What do you think?

**Comment by basz** [comment]
consider https://github.com/http-interop/http-middleware

**Comment by sandrokeil** [comment]
Close this in favor of #21 which solves this issue.
