### ISSUE TITLE
ResponseStrategy should be context aware

### ISSUE THREAD

**Issue by oqq** [prooph/psr7-middleware#14]
Hi!

Currently i see no clean way to provide some context metadata to response strategy.
As example it would be handy to use the request or the query that was dispatched to the query bus, to get the provided metadata.

``` php
final class HtmlResponseStrategy implements ResponseStrategy
{
    /** @var TemplateRendererInterface */
    private $templateRenderer;

    /**
     * @param TemplateRendererInterface $templateRenderer
     */
    public function __construct(TemplateRendererInterface $templateRenderer)
    {
        $this->templateRenderer = $templateRenderer;
    }

    /**
     * @inheritDoc
     */
    public function fromPromise(Promise $promise, array $context)
    {
        /** @var ServerRequestInterface $request */
        $request = $context['request'];
        $template = $request->getAttribute('template');

        $data = null;

        $promise->done(function($result) use (&$data) {
            $data = $result;
        });

        return new HtmlResponse(
            $this->templateRenderer->render($template),
            ['data' => $data]
        );
    }
}
```

Without $context i have create a abstract factory to inject the template name in the strategy, which would ends in a config nighmare.

Or am i missing a already existing solution for that issue?
Some hints would to be welcome.

Thanks!

**Comment by sandrokeil** [comment]
That's a good point. I guess we should look to issue #11 too. With this you could transform a JSON response to a HTML or XML  response. But maybe there is a better solution. At the moment I'm busy, but I can think more about that in the beginning of october.

I would like to avoid an additional parameter to the `fromPromise` method. /cc @bweston92

**Comment by oqq** [comment]
How about with a ResponseStrategyFactory?

``` php
$responseStrategy = $this->responseStrategyFactory->createStrategyFromRequest($request);

return $responseStrategy->fromPromise(
    $this->queryBus->dispatch($query)
);
```

**Comment by prolic** [comment]
@oqq @basz @sandrokeil Please move this issue to https://github.com/prooph/http-middleware/

**Comment by basz** [comment]
This issue was moved to prooph/http-middleware#2
