### ISSUE TITLE
Support for queries on standard projections

### ISSUE THREAD

**Issue by basz** [prooph/psr7-middleware#22]
on chat
> I'm thinking bout updating the middleware component to add support for queries on standard projections. Would that be useful?

> sounds good

It is possible to query standard projections. One QueryStandardProjection query could do it, but we would loose out on permissions etc.. so... quick and dirty

```
trait StandardQueryTrait {
 public function streamName(): string {
    return $this->metadata()['stream_name'];
 }

 public function result($state) {
   return $state;
  }
}
abstract class QueryStandardProjection extends Messaging\Query implements Messaging\PayloadConstructable  {
   use Messaging\StandardQueryTrait;
}

class StandardQueryHandler {
    private $projectionManager;

    public function __construct(ProjectionManager $projectionManager)
    {
        $this-> projectionManager = $projectionManager;
    }

    public function onEvent(QueryStandardProjection $query, Deferred $deferred)
    {
        // use projectionManager to retrieve state of $query->streamName()

      $deferred->resolve($query->makeResult($state));
    }
}

class MyQuery extends QueryStandardProjection {
   public function result($state) {
     return ValueObject::fromArray($state);
  }
}
```

routes
```
        [
            'name'            => 'query::something',
            'path'            => '/path',
            'middleware'      => [
                StandardQueryMiddleware::class,
            ],
            'allowed_methods' => ['OPTION', 'GET'],
            'options'         => [
                'values' => [
                    StandardQueryMiddleware::NAME_ATTRIBUTE => MyQuery::class,
                    StandardQueryMiddleware::STREAM_NAME => 'my_projection',
                ],
            ],
        ],

```

Which add a StandardQueryMiddleware. 

It's just an rough idea... Looking for input

**Comment by basz** [comment]
@prolic @sandrokeil @codeliner thoughts?

I now understand Query's as used in the standard projections are not traditional queries but rather projections without persisted state.... So that might skew this a little... Thought I needed to point that out...

**Comment by prolic** [comment]
I don't think it makes sense to have this as middleware. An event store query can use some time, it's more for answering some questions that arise from the business, where someone wants to know some stats f.e. and he is happy, when you give him the result the next few days. There is no need to have this exposed through the Api I think.

**Comment by basz** [comment]
This issue was moved to prooph/http-middleware#4
