### ISSUE TITLE
http-middleware-compatibility

### ISSUE THREAD

**Issue by basz** [prooph/psr7-middleware#27]
Is this something we should implement also? https://github.com/webimpress/http-middleware-compatibility.

like here: https://github.com/zendframework/zend-expressive-session/pull/2/files
or here : https://github.com/harikt/psr7-asset/pull/25/files

- [x] prooph/psr7-middleware
- [x] prooph/proophessor-do
- [x] prooph/event-store-http-api

**Comment by codeliner** [comment]
I like the idea and if expressive supports it, we should do the same ;)

**Comment by basz** [comment]
Just found out expressive doesn't support it - yet - PR's are ready though...

I'll create the appropriate PR's here

https://github.com/zendframework/zend-expressive/pull/517#issuecomment-335302764
