### ISSUE TITLE
Add to docs

### ISSUE THREAD

**Issue by basz** [prooph/psr7-middleware#31]
The docs from this repo don't show up on... http://docs.getprooph.org/

Can I help?

**Comment by prolic** [comment]
A lot of docs don't show up currently. I am not sure what the plan is here. @codeliner can you elaborate?

**Comment by codeliner** [comment]
https://github.com/prooph/proophessor/projects/1

issue related to your question @basz : https://github.com/prooph/proophessor/issues/67

Need to find time to continue docs refactoring. Annoying task that I can only do in chunks ;)

**Comment by prolic** [comment]
New repo is here: https://github.com/prooph/http-middleware/
