### ISSUE TITLE
Rename Package to psr15-middlewares

### ISSUE THREAD

**Issue by oqq** [prooph/psr7-middleware#35]
Since there would be a new PSR for middlewares with identifier PSR-15 sone, we should rename this repo before a stable release.

Also this changes here: https://github.com/prooph/psr7-middleware/pull/34
uses the http-interop vendor. This should be changed to the final psr/http-server-middleware once it is available.

**Comment by sandrokeil** [comment]
We should name it only `middleware` or `http-middleware` or follow the PSR repo naming but not PSR-15. Maybe it's not the last PSR.

**Comment by basz** [comment]
I agree with sandrokeil, also singular

**Comment by prolic** [comment]
We have created a new repo here: https://github.com/prooph/http-middleware/
