### ISSUE TITLE
Add possibility to get metadata from request

### ISSUE THREAD

**Issue by codeliner** [prooph/psr7-middleware#6]
It could be useful to get specific metadata from the psr7 request and create a command/event/query using the metadata. One example is an identity value object which was added by an authentication middleware to the request as an attribute. 

One option would be to inject a "MetadataGatherer" (maybe optional dependency or a noop default) to each message handling middleware. The creation of a message could then look something like this:

``` php
$query = $this->queryFactory->createMessageFromArray($queryName, [
  'payload' => $payload,
  'metadata' => $this->metadataGatherer->getFromRequest($request),
]);
```

**Comment by basz** [comment]
I kind of need this _now_. How can I help get this realised?

I see what a'metadataGatherer would do. I think I could create this, no one is working on this and a PR would be accepted?

**Comment by codeliner** [comment]
@basz PR would be great.

**Comment by basz** [comment]
Allready started

**Comment by codeliner** [comment]
Added with #7
